// <auto-generated />
using System;
using Kdan.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kdan.Migrations
{
    [DbContext(typeof(KdanContext))]
    [Migration("20230818074512_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_bin")
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Kdan.Models.KdanMembers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("int")
                        .HasComment("流水編號");

                    b.Property<DateTime?>("ClockIn")
                        .HasColumnType("datetime(6)")
                        .HasComment("上班打卡時間");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("datetime(6)")
                        .HasComment("下班打卡時間");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasComment("員工編號");

                    b.HasKey("Id");

                    b.ToTable("members", null, t =>
                        {
                            t.HasComment("員工打卡時間");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
